import { Sidebar } from "@/components";
import "../../globals.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Duc Vy",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex content bg-[#F6F7F9]">
      <Sidebar />
      <div className="w-full ml-16 bg-white border-2 rounded-md">
        {children}
      </div>
    </div>
  );
}
