import { Sidebar } from "@/components";

export const metadata = {
  title: "Order",
  description: "Generated by Duc Vy",
};

export default function OrderLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="content grid grid-cols-5 bg-[#F6F7F9]">
      <Sidebar />
      <div className="col-span-4 bg-white ml-16 border-2 rounded-md">
        {children}
      </div>
    </div>
  );
}
