import { Sidebar } from "@/src/components";

export const metadata = {
  title: "Car",
  description: "Generated by Duc Vy",
};

export default function CarLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="content grid grid-cols-5 bg-[#F6F7F9]">
      <Sidebar />
      <div className="col-span-4 bg-white ml-16 border-2 rounded-md">
        {children}
      </div>
    </div>
  );
}
