import { Sidebar } from "@/src/components";
import "../../../globals.css";

export const metadata = {
  title: "CarView",
  description: "Generated by Duc Vy",
};

export default function CarViewLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
