import "../../../globals.css";

export const metadata = {
  title: "Order View",
  description: "Generated by Duc Vy",
};

export default function OrderViewLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
