import { Sidebar } from "@/components";
import "../globals.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Duc Vy",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="content grid grid-cols-5">
      <Sidebar />
      {children}
    </div>
  );
}
